---
sudo: required
dist: trusty

language: python
python: "2.7"

env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.1.2
  - ANSIBLE_VERSION=2.1.1.0
  - ANSIBLE_VERSION=2.1.0.0
  - ANSIBLE_VERSION=2.0.2.0
  - ANSIBLE_VERSION=2.0.1.0
  - ANSIBLE_VERSION=2.0.0.2
  - ANSIBLE_VERSION=2.0.0.1
  - ANSIBLE_VERSION=2.0.0.0
  - ANSIBLE_VERSION=1.9.6
  - ANSIBLE_VERSION=1.9.5
  - ANSIBLE_VERSION=1.9.4
  - ANSIBLE_VERSION=1.9.3
  - ANSIBLE_VERSION=1.9.2
  - ANSIBLE_VERSION=1.9.1
  - ANSIBLE_VERSION=1.9.0.1
  - ANSIBLE_VERSION=1.8.4
  - ANSIBLE_VERSION=1.8.3
  - ANSIBLE_VERSION=1.8.2
  - ANSIBLE_VERSION=1.8.1
  - ANSIBLE_VERSION=1.8
  - ANSIBLE_VERSION=1.7.2
  - ANSIBLE_VERSION=1.7.1
  - ANSIBLE_VERSION=1.7
  - ANSIBLE_VERSION=1.6.9
  - ANSIBLE_VERSION=1.6.8
  - ANSIBLE_VERSION=1.6.7
  - ANSIBLE_VERSION=1.6.6
  - ANSIBLE_VERSION=1.6.5
  - ANSIBLE_VERSION=1.6.4
  - ANSIBLE_VERSION=1.6.3
  - ANSIBLE_VERSION=1.6.2
  - ANSIBLE_VERSION=1.6.10
  - ANSIBLE_VERSION=1.6.1
  - ANSIBLE_VERSION=1.6

matrix:
  allow_failures:
    # swapon operation is not permitted
    - env: ANSIBLE_VERSION=latest
    - env: ANSIBLE_VERSION=1.9.4
    - env: ANSIBLE_VERSION=1.9.3
    - env: ANSIBLE_VERSION=1.9.2
    - env: ANSIBLE_VERSION=1.9.1
    - env: ANSIBLE_VERSION=1.9.0.1
    - env: ANSIBLE_VERSION=1.8.4
    - env: ANSIBLE_VERSION=1.8.3
    - env: ANSIBLE_VERSION=1.8.2
    - env: ANSIBLE_VERSION=1.8.1
    - env: ANSIBLE_VERSION=1.8
    - env: ANSIBLE_VERSION=1.7.2
    - env: ANSIBLE_VERSION=1.7.1
    - env: ANSIBLE_VERSION=1.7
    - env: ANSIBLE_VERSION=1.6.9
    - env: ANSIBLE_VERSION=1.6.8
    - env: ANSIBLE_VERSION=1.6.7
    - env: ANSIBLE_VERSION=1.6.6
    - env: ANSIBLE_VERSION=1.6.5
    - env: ANSIBLE_VERSION=1.6.4
    - env: ANSIBLE_VERSION=1.6.3
    - env: ANSIBLE_VERSION=1.6.2
    - env: ANSIBLE_VERSION=1.6.10
    - env: ANSIBLE_VERSION=1.6.1
    - env: ANSIBLE_VERSION=1.6

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install --no-binary ansible ansible; else pip install --no-binary ansible ansible==$ANSIBLE_VERSION; fi

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i tests/inventory tests/test.yml -vvvv

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i tests/inventory tests/test.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  email: false
  hipchat:
    rooms:
      secure: SivIIyIfrzgQ/crgx9+JLxNhMGCGX/SggBkR59GdBx7tKjLKUReqHuG0NvJd6m0sYgaJqWVYnpXThwWPa7+k+PvisVf/RrfKWzmfK11WZctgq9JDZxrNnHROVgrNvoVKebD/pj0ZtLaMff+ECmBkRGnurFbIMXhT6StxHlPqiEE=
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
