---
# tasks file for swapfile
- name: write swap file
  command: fallocate -l {{ swapfile_size }} /swap creates=/swap
  register: write_swapfile
  when: swapfile_size != False
  tags: [configuration, swap]

- name: set swap file permissions
  file:
    path: /swap
    owner: root
    group: root
    mode: 600
  when: swapfile_size != False
  tags: [configuration, swap]

- name: create swap file
  command: mkswap /swap
  register: create_swapfile
  when: swapfile_size != False and write_swapfile.changed
  tags: [configuration, swap]

- name: enable swapfile
  command: swapon /swap
  when: swapfile_size != False and create_swapfile.changed
  tags: [configuration, swap]

- name: add swapfile to /etc/fstab
  mount:
    name: none
    src: /swap
    fstype: swap
    opts: sw
    passno: 0
    dump: 0
    state: present
  tags: [configuration, swap]

- name: configure vm.swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ swapfile_swappiness }}"
    state: present
  notify: reload sysctl
  when: swapfile_swappiness != false
  tags: [configuration, swap]

- name: configure vm.vfs_cache_pressure
  sysctl:
    name: vm.vfs_cache_pressure
    value: "{{ swapfile_vfs_cache_pressure }}"
    state: present
  notify: reload sysctl
  when: swapfile_vfs_cache_pressure != false
  tags: [configuration, swap]
