---
# tasks file for swapfile
- name: write swap file
  command: fallocate -l {{ swapfile_size }} /swap creates=/swap
  register: write_swapfile
  when: swapfile_size != false
  tags: [configuration, swap]

- name: set swap file permissions
  file: path=/swap mode=600
  when: swapfile_size != false
  tags: [configuration, swap]

- name: create swap file
  command: mkswap /swap
  register: create_swapfile
  when: swapfile_size != false and write_swapfile.changed
  tags: [configuration, swap]

- name: enable swapfile
  command: swapon /swap
  when: swapfile_size != false and create_swapfile.changed
  tags: [configuration, swap]

- name: add swapfile to /etc/fstab
  lineinfile: dest=/etc/fstab line="/swap   none    swap    sw    0   0" state=present
  when: swapfile_size != false
  tags: [configuration, swap]

- name: configure vm.swappiness
  lineinfile: dest=/etc/sysctl.conf line="vm.swappiness = {{ swapfile_swappiness }}" regexp="^vm.swappiness[\s]?=" state=present
  notify: reload sysctl
  when: swapfile_swappiness != false
  tags: [configuration, swap]

- name: configure vm.vfs_cache_pressure
  lineinfile: dest=/etc/sysctl.conf line="vm.vfs_cache_pressure = {{ swapfile_vfs_cache_pressure }}" regexp="^vm.vfs_cache_pressure[\s]?=" state=present
  notify: reload sysctl
  when: swapfile_vfs_cache_pressure != false
  tags: [configuration, swap]
